#- hosts: LAMP
#  name: install Wordpress
#  remote_user: centos

#  tasks:

  - name: Include vars of vars.yaml
    include_vars:
      file: ../../../vars/vars.yml

  - name: Download WordPress
    get_url:
      url=https://wordpress.org/latest.tar.gz
      dest=/tmp/wordpress.tar.gz
      validate_certs=no

  - name: Extract WordPress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html copy=no
#    become: true

  - name: Copy sample config file
    command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
#    become: true

  - name: Update WordPress config file
    lineinfile:
      dest: /var/www/html/wordpress/wp-config.php
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_db}}');"}
      - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_user}}');"}
      - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_user_password}}');"}
#    become: true

  - file:
      path: /var/www/html
      owner: apache
      group: apache
      mode: 02754
      recurse: yes
#    become: true
