---
- hosts: LAMP

#  remote_user: centos

  vars:
    mysql_root_password: lalala
    wp_user: wp_user
    wp_db: wp_db

  tasks:
#:10,15s/^/#
  - name: update all packages
    yum:
      name: '*'
      state: latest

  - name: Add epel repository
    yum_repository:
      name: epel
      description: EPEL YUM repo
      baseurl: https://download.fedoraproject.org/pub/epel/$releasever/$basearch/
      enabled: 1
      gpgcheck: no  

  - name: Add repository webtatic-release
    yum_repository:
      name: webtatic
      description: webtatic repo
      baseurl: https://repo.webtatic.com/yum/el7/$basearch/
      mirrorlist: https://mirror.webtatic.com/yum/el7/$basearch/mirrorlist
      enabled: 1
      gpgcheck: no

  - name: Install packages
    yum: 
      name: "{{ item }}" 
      state: latest
    with_items:
         - httpd
         - mariadb-server
         - mod_php72w
         - php72w-opcache
         - php72w-mysqlnd
         - MySQL-python
         - mod_ssl

  - name: yum-clean-metadata
    command: yum clean metadata
    args:
      warn: no

  - name: ensure apache is running (and enable it at boot)
    service:
      name: httpd
      state: started
      enabled: yes

  - name: ensure mariadb is running (and enable it at boot)
    service:
      name: mariadb
      state: started
      enabled: yes

  #SELinux configuration
  - sefcontext:
      target: '/var/www/html(/.*)?'
      setype: httpd_sys_content_t
      state: present        
  - sefcontext:
      target: '/var/lib/mysql(/.*)?'
      setype: mysqld_db_t
      state: present        

  - name: Copying the root credentials as .my.cnf file
    template: src=templates/my.cnf dest=~/.my.cnf owner=root group=root mode=0600

  - name: Set MariaDB root password
    mysql_user:
      name: root
      password: "{{ mysql_root_password }}"
      check_implicit_admin: yes

  - name: mysql_sercure_installation
    command: 'mysql -ne "{{ item }}"'
    with_items:
      - DELETE FROM mysql.user WHERE User='' #remove anonymous users
      - DELETE FROM mysql.user WHERE User='root' AND Host NOT IN ('localhost', '127.0.0.1', '::1') #disallow root login remotely
      - DROP DATABASE IF EXISTS test #Remove test database and access to it
      - DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%' #Remove test database and access to it
      - FLUSH PRIVILEGES #Reload privilege tables
    changed_when: False

  - name: Creating a new database with name 'wp_db'
    mysql_db:
      name: wp_db
      state: present
      login_user: root
      login_password: "{{ mysql_root_password }}"

  - name: Creating database user
    mysql_user:
      name: wp_user
      password: "{{ mysql_root_password }}"
      priv: 'wp_db.*:ALL,GRANT'
      state: present
  
  - name: copying httpd.conf
    copy:
      src: files/httpd.conf
      dest: /etc/httpd/conf/httpd.conf
      owner: root
      group: root
      mode: 0644  
      backup: yes

  - name: copying ssl.conf
    copy:
      src: files/ssl.conf
      dest: /etc/httpd/conf.d/ssl.conf
      owner: root
      group: root
      mode: 0644  
      backup: yes

  - name: copying virtualhost.conf
    copy:
      src: files/virtualhost.conf
      dest: /etc/httpd/conf.d/virtualhost.conf
      owner: root
      group: root
      mode: 0644

  - name: creating virtualhost directory
    file:
      path: /var/www/html/wordpress
      state: directory
      owner: apache
      group: apache
      mode: 0775

  - name: Download WordPress
    get_url: 
      url=https://wordpress.org/latest.tar.gz 
      dest=/tmp/wordpress.tar.gz
      validate_certs=no

  - name: Extract WordPress
    unarchive: src=/tmp/wordpress.tar.gz dest=/var/www/html copy=no
 
  - name: Copy sample config file
    command: mv /var/www/html/wordpress/wp-config-sample.php /var/www/html/wordpress/wp-config.php
  
  - name: Update WordPress config file
    lineinfile:
      dest: /var/www/html/wordpress/wp-config.php
      regexp: "{{ item.regexp }}"
      line: "{{ item.line }}"
    with_items:
      - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_db}}');"}        
      - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_user}}');"}        
      - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{mysql_root_password}}');"}

  - name: creating virtualhost directory
    file:
      path: /var/www/html/wordpress
      owner: apache
      group: apache
      recurse: yes

  - name: Update php.ini
    lineinfile:
      dest: /etc/php.ini
      regexp: '^expose_php'
      line: 'expose_php = Off'

  - name: restarting services
    command: echo "this task will restart all services"
    notify: "restart services"
  
  handlers:
    - name: restart mariadb
      service:
        name: mariadb
        state: restarted
      listen: "restart services"
    - name: restart httpd
      service:
        name: httpd
        state: restarted
      listen: "restart services"
